// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type GuitarType string

const (
	GuitarTypeElectric  GuitarType = "electric"
	GuitarTypeAcoustic  GuitarType = "acoustic"
	GuitarTypeClassical GuitarType = "classical"
	GuitarTypeOther     GuitarType = "other"
)

func (e *GuitarType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuitarType(s)
	case string:
		*e = GuitarType(s)
	default:
		return fmt.Errorf("unsupported scan type for GuitarType: %T", src)
	}
	return nil
}

type NullGuitarType struct {
	GuitarType GuitarType
	Valid      bool // Valid is true if GuitarType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuitarType) Scan(value interface{}) error {
	if value == nil {
		ns.GuitarType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuitarType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuitarType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuitarType), nil
}

type MediaKind string

const (
	MediaKindImage MediaKind = "image"
	MediaKindVideo MediaKind = "video"
)

func (e *MediaKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaKind(s)
	case string:
		*e = MediaKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaKind: %T", src)
	}
	return nil
}

type NullMediaKind struct {
	MediaKind MediaKind
	Valid     bool // Valid is true if MediaKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaKind) Scan(value interface{}) error {
	if value == nil {
		ns.MediaKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaKind), nil
}

type SpecSource string

const (
	SpecSourceManufacturer SpecSource = "manufacturer"
	SpecSourceEditor       SpecSource = "editor"
	SpecSourceUser         SpecSource = "user"
)

func (e *SpecSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpecSource(s)
	case string:
		*e = SpecSource(s)
	default:
		return fmt.Errorf("unsupported scan type for SpecSource: %T", src)
	}
	return nil
}

type NullSpecSource struct {
	SpecSource SpecSource
	Valid      bool // Valid is true if SpecSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpecSource) Scan(value interface{}) error {
	if value == nil {
		ns.SpecSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpecSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpecSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpecSource), nil
}

type SpecValueType string

const (
	SpecValueTypeText   SpecValueType = "text"
	SpecValueTypeNumber SpecValueType = "number"
	SpecValueTypeBool   SpecValueType = "bool"
	SpecValueTypeEnum   SpecValueType = "enum"
)

func (e *SpecValueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpecValueType(s)
	case string:
		*e = SpecValueType(s)
	default:
		return fmt.Errorf("unsupported scan type for SpecValueType: %T", src)
	}
	return nil
}

type NullSpecValueType struct {
	SpecValueType SpecValueType
	Valid         bool // Valid is true if SpecValueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpecValueType) Scan(value interface{}) error {
	if value == nil {
		ns.SpecValueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpecValueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpecValueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpecValueType), nil
}

type Brand struct {
	ID   string
	Name string
}

type Guitar struct {
	ID          string
	Slug        string
	Name        string
	BrandID     string
	Model       string
	Type        string
	Year        pgtype.Int4
	Description pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GuitarMedium struct {
	ID        string
	GuitarID  string
	Kind      string
	Url       string
	SortOrder int32
}

type GuitarSpecValue struct {
	GuitarID      string
	SpecID        string
	ValueText     pgtype.Text
	ValueNumber   pgtype.Numeric
	ValueBool     pgtype.Bool
	ValueOptionID pgtype.UUID
	Source        NullSpecSource
}

type Spec struct {
	ID         string
	Code       string
	Label      string
	ValueType  string
	Unit       pgtype.Text
	Filterable bool
	Searchable bool
	GuitarType NullGuitarType
}

type SpecOption struct {
	ID        string
	SpecID    string
	Value     string
	SortOrder int32
}
